name: release

on:
  push:
    branches:
      - '*'
    tags:
      - '*.*.*.*'

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Publish
      run: >
        "dotnet publish GHReleaseTest/ConsoleApp1/ConsoleApp1.csproj
        -c Release
        -r ${{ fromJson('{ \"windows-latest\": \"win10-x64\", \"ubuntu-latest\": \"linux-x64\", \"macos-latest\": \"osx-x64\" }')[matrix.os] }}
        -o tmp
        -p:PublishReadyToRun=${{ (matrix.os == 'windows-latest' && 'true') || 'false' }}
        -p:PublishSingleFile=true
        -p:PublishTrimmed=true
        --self-contained true"
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifact-${{ matrix.os }}
        path: tmp/*
