name: release

on:
  push:
    branches:
      - '*'
    tags:
      - '*.*.*'
  workflow_dispatch:
jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    env:
      RELEASE_PREFIX: Artifact
    steps:
    - uses: actions/checkout@v2
    - uses: FranzDiebold/github-env-vars-action@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Build
      run: >
        dotnet publish GHReleaseTest/ConsoleApp1/ConsoleApp1.csproj
        -c Release
        -r ${{ fromJson('{ "windows-latest": "win10-x64", "ubuntu-latest": "linux-x64", "macos-latest": "osx-x64" }')[matrix.os] }}
        -o tmp
        -p:PublishReadyToRun=${{ (matrix.os == 'windows-latest' && 'true') || 'false' }}
        -p:PublishSingleFile=true
        -p:PublishTrimmed=true
        --self-contained true
      env:
        APP_VERSION: ${{ (contains(github.ref, 'tags/') && env.CI_ACTION_REF_NAME) || '0.0.1' }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.RELEASE_PREFIX }}-${{ matrix.os }}
        path: tmp/*

    - name: Archive
      uses: vimtor/action-zip@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        recursive: false
        files: tmp
        dest: ${{ env.RELEASE_PREFIX }}-${{ matrix.os }}.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ env.RELEASE_PREFIX }}-${{ matrix.os }}.zip
        name: v${{ env.CI_ACTION_REF_NAME }}
        draft: true
        prerelease: false
